export const MOVIE_GENRES = {
    AC: 'Action',
    AD: 'Adventure',
    CO: 'Comedy',
    CR: 'Crime',
    DR: 'Drama',
    FA: 'Fantasy',
    HI: 'Historical',
    HO: 'Horror',
    MY: 'Mystery',
    PO: 'Political',
    RO: 'Romance',
    TH: 'Thiller',
    WE: 'Western',
}