export const AUTH_USER = 'AUTH_USER';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_MOVIES = 'GET_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const SET_MOVIE = 'SET_MOVIE';

export const ADD_LIKE = 'ADD_LIKES';
export const UPDATE_MOVIE_LIKES = 'UPDATE_MOVIE_LIKES';
export const REMOVE_LIKE = 'REMOVE_LIKE';
export const REMOVE_MOVIE_LIKE = 'REMOVE_MOVIE_LIKE';
export const INCREMENT_VISITS = 'INCREMENT_VISITS';
export const UPDATE_MOVIE_VISITS = 'UPDATE_MOVIE_VISITS';

export const POST_COMMENT = 'POST_COMMENT';
export const PUT_MOVIE_COMMENT = 'PUT_MOVIE_COMMENT';
export const GET_COMMENTS = 'GET_COMMENTS';
export const UPDATE_MOVIE_COMMENTS = 'UPDATE_MOVIE_COMMENTS';