export const AUTH_USER = 'AUTH_USER';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_MOVIES = 'GET_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const SET_MOVIE = 'SET_MOVIE';

export const ADD_LIKE = 'ADD_LIKE';
export const UPDATE_MOVIE_LIKES = 'UPDATE_MOVIE_LIKES';
export const REMOVE_LIKE = 'REMOVE_LIKE';
export const REMOVE_MOVIE_LIKE = 'REMOVE_MOVIE_LIKE';
export const INCREMENT_VISITS = 'INCREMENT_VISITS';
export const UPDATE_MOVIE_VISITS = 'UPDATE_MOVIE_VISITS';

export const GET_WATCHLIST = 'GET_WATCHLIST';
export const UPDATE_WATCHLIST = 'UPDATE_WATCHLIST';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const PUT_MOVIE_INTO_WATCHLIST = 'PUT_MOVIE_INTO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const PUT_MOVIE_OUT_OF_WATCHLIST = 'PUT_MOVIE_OUT_OF_WATCHLIST';
export const UPDATE_WATCHED = 'UPDATE_WATCHED';
export const UPDATE_MOVIE_IN_WATCHLIST = 'UPDATE_MOVIE_IN_WATCHLIST';